[!110] Update dependencies and minimum supported Rust version
- Update dependencies

  This was done manually, but I used a tool to help me find the outdated versions:

  1. `cargo install cargo-outdated`. This is a tool to detect dependencies that are out of date.
  2. `cargo outdated --root-deps-only`. This shows the top-level dependencies, without showing transient dependencies (like `serial_test_derive` and `clang-sys`).
  3. Fix the breakage from updating. In particular I found that `rt-core` was removed in tokio 1.0:

  ```
  > cargo check
      Updating crates.io index
  error: failed to select a version for `tokio`.
      ... required by package `yottadb v1.1.0 (/home/joshua/src/yottadb/YDBRust)`
  versions that meet the requirements `^1` are: 1.0.1

  the package `yottadb` depends on `tokio`, with features: `rt-core` but `tokio` does not have these features.
  ```

  and that `rand` had a breaking change:

  ```
  error[E0061]: this function takes 1 argument but 2 arguments were supplied
    --> examples/random_walk.rs:29:19
     |
  29 |     let val = rng.gen_range(0, 2);
     |                   ^^^^^^^^^ -  - supplied 2 arguments
     |                   |
     |                   expected 1 argument
  ```

  I fixed those errors and also cleaned up `get_global` a little while I was at it.

- This also fixes the `Context` doc-test, which, again, was failing for
  the wrong reasons.

  The previous error was

  ```
  error[E0308]: mismatched types
    --> src/context_api/mod.rs:154:19
     |
  12 |     ctx.tp(|_| Ok(()), "BATCH", &[])
     |                   ^^ expected enum `TransactionStatus`, found `()`
  ```

  which is left over from https://gitlab.com/YottaDB/Lang/YDBRust/-/merge_requests/65 (a full 9 months ago!). I fixed it to now give the correct error:

  ```

  failures:

  ---- src/context_api/mod.rs - context_api::Context (line 144) stdout ----
  error[E0277]: `Rc<RefCell<context_api::ContextInternal>>` cannot be shared between threads safely
     --> src/context_api/mod.rs:151:1
      |
  10  | tokio::spawn(async {
      | ^^^^^^^^^^^^ `Rc<RefCell<context_api::ContextInternal>>` cannot be shared between threads safely
      |
     ::: /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/task/spawn.rs:128:21
      |
  128 |         T: Future + Send + 'static,
      |                     ---- required by this bound in `tokio::spawn`
      |
      = help: within `yottadb::context_api::Context`, the trait `Sync` is not implemented for `Rc<RefCell<context_api::ContextInternal>>`
      = note: required because it appears within the type `yottadb::context_api::Context`
      = note: required because of the requirements on the impl of `Send` for `&yottadb::context_api::Context`
      = note: required because it appears within the type `[static generator@src/context_api/mod.rs:10:20: 13:2 _]`
      = note: required because it appears within the type `from_generator::GenFuture<[static generator@src/context_api/mod.rs:10:20: 13:2 _]>`
      = note: required because it appears within the type `impl Future`
  ```

  The issue was that Rust does not have a stable way to test that a test gives a *specific* error instead of failing to compile. On nightly there is a way: https://doc.rust-lang.org/rustdoc/unstable-features.html#error-numbers-for-compile-fail-doctests and I added it, but it will only have an effect on nightly toolchains. Since [we test on nightly](https://gitlab.com/YottaDB/Lang/YDBRust/-/blob/b7980d49be62e890ac3246573bf02e1239086994/.gitlab-ci.yml#L67), the hope is we'll notice relatively quickly if it starts to fail for the wrong reason again; even though `allow_failure` is set, it will still show up in the 'pipeline' view on GitLab I think.

  Note that you can find these error messages by removing `compile_fail` then running `cargo test --doc context_api::Context` locally, just remember to add back `compile_fail` when you're done.

  All the other changes to context_api are just cleanups (e.g. changing `#[macro_use]` to a normal path import).

- Increase minimum supported version

  Bindgen 0.56 no longer supports rust 1.34, so the MSRV was also
  increased to 1.40. Unfortunately, this exposed an issue with cargo:
  although `profile.release.package."*"` was ignored on 1.34 (since it was
  unsupported), in 1.40 it gives an error that it requires nightly
  features. For now, remove the feature. It may be possible to enable it
  for toolchains that support it by setting
  `CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_OPT_LEVEL=0` in the environment,
  but that would require a toolchain of at least version 1.41, which I'm
  not sure is currently the case for our internal test suite.

  Note that the feature was enabled by default in Cargo 1.49 (https://github.com/rust-lang/cargo/pull/8500),
  so there is a very small window of toolchains where the environment
  variable would have an effect.