[Pipeline] Fix 3 issues with rust-latest pipeline
`cargo fmt -- --check` issued warnings for `fn_args_layout`. Renamed to
`fn_params_layout`.
```
Warning: the `fn_args_layout` option is deprecated. Use `fn_params_layout`. instead
```

Remove `mut` per this warning:
```
warning: variable does not need to be mutable
   --> src/simple_api/mod.rs:929:29
    |
929 |                 if let Some(mut ydb_err) = err.downcast_mut::<YDBError>() {
    |                             ----^^^^^^^
    |                             |
    |                             help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default
```

The last warning check was more difficult to troubleshoot as it would require
major changes to the code. @jyn514 suggested to suppress the warning instead by
adding `#[allow(clippy::redundant_closure_call)]`.
```
error: try not to call a closure in the expression where it is declared
    --> src/context_api/mod.rs:60:30
     |
60   |                       Ok(_) => $next(self),
     |                                ^^^^^^^^^^^
...
1485 | / implement_iterator!(
1486 | |     ForwardValueIterator,
1487 | |     next_sub_self,
1488 | |     Vec<u8>,
1489 | |     |me: &mut ForwardValueIterator| { Some(me.key.get()) }
1490 | | );
     | |_- in this macro invocation
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure_call
     = note: `-D clippy::redundant-closure-call` implied by `-D clippy::all`
     = note: this error originates in the macro `implement_iterator` (in Nightly builds, run with -Z macro-backtrace for more info)
```