[YottaDB/DB/YDB#564] Fix ydb_ci_t() unit test in tests/infinite_inv_str.rs now that INVSTRLEN error is not returned
Background
----------
* The `rust-latest` scheduled pipeline job started failing with the following symptom.

* Below is from an example failure at https://gitlab.com/YottaDB/Lang/YDBRust/-/jobs/3246442440.

  ```
  test ydb_ci_t ... FAILED
  failures:
  ---- ydb_ci_t stdout ----
  thread 'ydb_ci_t' panicked at 'called `Result::unwrap_err()` on an `Ok` value: []', tests/infinite_inv_str.rs:40:82
  ```

Issue
-----
* The `ydb_ci_t` test expected an `INVSTRLEN` error when the `out_buffer` for a `ydb_ci_t()` SimpleThreadAPI
  call did not have enough space to hold the return value from the call-in.

* This behavior was changed recently as part of YottaDB/DB/YDB#564 (YottaDB/DB/YDB@c3691d3f) to return a
  truncated string instead of issuing an `INVSTRLEN` error.

Fix
---
* The `ydb_ci_t` test is reworked to now expect no `INVSTRLEN` error but instead expect an empty string
  return value.