[Pipeline] Disable rust-latest, bump rust ver for compat
`rust-latest` disabled due to
https://gitlab.com/YottaDB/Lang/YDBRust/-/issues/54. Pages job updated
to rely on `rust-compat`.

`rust-compat` version bumped up from 1.65 to 1.71 for this:
```
error: package `libloading v0.8.9` cannot be built because it requires rustc 1.71.0 or newer, while the currently active rustc version is 1.65.0
Either upgrade to rustc 1.71.0 or newer, or use
cargo update -p libloading@0.8.9 --precise ver
where `ver` is the latest version of `libloading` supporting rustc 1.65.0
```

- Failing `rust-latest` pipeline: https://gitlab.com/YottaDB/Lang/YDBRust/-/jobs/11434954097
- Failing `rust-compat` pipeline: https://gitlab.com/YottaDB/Lang/YDBRust/-/jobs/11434954091