Silence buggy clippy lint
The lint looked like this:

```
error: name `YDB` contains a capitalized acronym
 --> src/context_api/mod.rs:747:5
 |
747 | YDB(YDBError),
 | ^^^ help: consider making the acronym lowercase, except the initial letter: `Ydb`
 |
 = note: `-D clippy::upper-case-acronyms` implied by `-D clippy::all`
 = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
```

This is a bug in clippy: `YDB` is a public enum variant, and it would be
a breaking change to change the name: https://github.com/rust-lang/rust-clippy/issues/6803

This silences the lint until it's fixed upstream.