[Pipeline] Bump up version of rust-compat due to upstream package changes
Pipeline https://gitlab.com/YottaDB/Lang/YDBRust/-/jobs/4157555771 show this error:

```
  Downloaded regex-syntax v0.7.1
error: failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.7.1/Cargo.toml`
Caused by:
  failed to parse the `edition` key
Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

This is caused by using an old version of Rust and Cargo.

It looks like the changes were due to commits done yesterday in
https://github.com/rust-lang/regex. I don't exactly know exactly what has
changed, but the author is well known in the Rust Community.

They bumpted the version to 1.60.0 here:
https://github.com/rust-lang/regex/commit/070374f2878f23809a4e5ca0810d523f692c6e7e
(the actual change was done in another commit; this is where it's documented).