[#13] Fix race conditions in test suite
- Switch from `#[serial]` to RwLock

  This orders the tests which must be run in serial with respect to
  *all* other tests, not just tests marked with `#[serial]`. In
  particular, when a test has a write lock out, no other test will be
  running concurrently. This is different from a mutex, where either a
  read or write lock will prevent other concurrent tests, because there
  can be multiple tests with a read lock running concurrently. Previously,
  `serial_test` would only prevent tests marked with `#[serial]` from
  running concurrently with each other; it was possible for another test
  to run in parallel with a serial test.

- Add a global `TEST_LOCK` using `once_cell`

  `once_cell` is a dependency from crates.io. `"1"` is the version
  number, and means "any version of `once_cell` with a major version of 1".

  There is more documentation about once_cell itself at
  https://docs.rs/once_cell/1/once_cell/. It is a very commonly used
  crate, and there are proposals to make it part of the standard library:
  https://github.com/rust-lang/rfcs/pull/2788.

- Add `Context::write_lock` wrapper

  `write_lock` is basically the same as `LockGuard::write`, but is
  stored in the `Context` and dropped automatically. This is not
  particularly more convenient; the reason I added it is so I could put a
  read lock in Context by default, to avoid accidentally missing a lock
  (like I did for the `simple_api` originally). Note that write_lock takes
  care of dropping the read lock so the tests won't deadlock; I originally
  had issues with deadlocks before adding the wrapper function.

- Don't use conflicting variable names for tests
- Fix races in `simple_api::call_in` tests with write guards

  Previously, the following error would occur about once every 5 runs:

  ```
  ---- simple_api::call_in::test::string_args stdout ----
  thread 'simple_api::call_in::test::string_args' panicked at 'called `Result::unwrap()` on an `Err` value: YDB Error (-150379666): 150379666,(SimpleThreadAPI),%YDB-E-CINOENTRY, No ', src/simple_api/call_in.rs:315:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

  The issue was that multiple tests were modifying the active call-in
  table. Now that the tests take out a write lock, the lock ensures that
  no two tests will be running at the same time when the call-in table is
  modified. This is slightly heavier of a hammer than necessary, because
  only tests making call-ins could possibly interfere, but the test suite
  runs fast enough I don't think it's worth improving.

- Add read guards to all other tests that have asserts

  If a test does not take out either a read or write lock, it could run
  concurrently with tests with a write lock. There are a very few tests
  that can do this without failing. For example, `can_make_key` does not
  ever make a call to the YDB engine, so it can't view any process-wide
  state, making it safe to run unsynchronized. Any test doing `get`s or
  `set`s could fail though, because the `ydb_delete_excl_st` test deletes
  *all* process-local variables. In other words, adding an `assert!` and
  read lock is the rule; not needing a read lock is the exception.