Update toolchains pinned in CI
- 1.40 is no longer supported by bindgen:

```
error[E0723]: loops and conditional expressions are not stable in const fn
   --> /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.56.0/src/codegen/mod.rs:100:1
    |
100 | / bitflags! {
101 | |     struct DerivableTraits: u16 {
102 | |         const DEBUG       = 1 << 0;
103 | |         const DEFAULT     = 1 << 1;
...   |
111 | |     }
112 | | }
    | |_^
    |
    = note: for more information, see issue https://github.com/rust-lang/rust/issues/57563
    = help: add `#![feature(const_fn)]` to the crate attributes to enable
```

- The latest stable release (1.55) no longer breaks cargo deadlinks.