[!133] Fix doc-example for str2zwr() to PASS in M mode too
Background
----------
* I noticed the following failure while running `cargo test` in-house.

  ```
  ---- src/context_api/mod.rs - context_api::Context::str2zwr (line 477) stdout ----
  Test executable failed (exit code 101).

  stderr:
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `[36, 67, 40, 50, 53, 53, 41]`,
   right: `[36, 90, 67, 72, 40, 50, 53, 53, 41]`', src/context_api/mod.rs:9:1
  ```

Issue
-----
* The `doc-example` test for `str2zwr()` was expecting that when the input is an invalid UTF-8,
  it will use the more verbose Zwrite format. And so it was expecting the return value of `$ZCH(255)`
  when the input string `\xff` was passed (this was a test added in c95de59 as part of !133).

* This was true in UTF-8 mode which is how the YDBRust pipeline runs. But in-house I was running in
  M mode and in that case, the string `$C(255)` is returned.

Fix
---
* The test is enhanced to expect `$ZCH(255)` in UTF-8 mode and `$C(255)` in M mode.
  This should let is continue to pass in the pipeline as well as pass in-house.