Fix a few clippy AND deadlinks warnings in src/simple_api/mod.rs
Issue 1 : Failure in rust-latest pipeline job from [cargo clippy]
=================================================================

Background
----------
* The `rust-latest` pipeline job started failing from Dec 15, 2022 onwards.

* Below is pasted from https://gitlab.com/YottaDB/Lang/YDBRust/-/jobs/3483430363, the first failure.

  ```
  Compiling yottadb v2.0.0 (/builds/YottaDB/Lang/YDBRust)
  error: casting to the same type is unnecessary (`i32` -> `i32`)
     --> src/simple_api/mod.rs:863:20
      |
  863 |             return YDB_TP_ROLLBACK as i32;
      |                    ^^^^^^^^^^^^^^^^^^^^^^ help: try: `YDB_TP_ROLLBACK`
      |
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
      = note: `-D clippy::unnecessary-cast` implied by `-D clippy::all`
  error: casting to the same type is unnecessary (`i32` -> `i32`)
     --> src/simple_api/mod.rs:876:17
      |
  876 |                 YDB_TP_ROLLBACK as i32
      |                 ^^^^^^^^^^^^^^^^^^^^^^ help: try: `YDB_TP_ROLLBACK`
      |
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
  error: could not compile `yottadb` due to 2 previous errors
  ```

Issue
-----
* `clippy 1.66` was released on Dec 15, 2022.
  See https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-166 for details.

* Although I don't know exactly how (meaning exact commit etc.), that release made the change so
  `clippy::all` implied `clippy::unnecessary-cast`.

* And this caught longstanding `unnecessary-cast` type of warnings in `src/simple_api/mod.rs`.

Fix
---
* The fix is to remove the `as i32` usages that should automatically address the `unnecessary-cast` warning.

Issue 2 : Failure in pages pipeline job from [cargo deadlinks]
=================================================================

* The above changes fixed the `rust-latest` pipeline job failure. But then the `pages` job started failing.
  Till now, it was never run (it is in the 2nd stage of jobs and because `rust-latest` job failed in the
  1st stage, the 2nd stage was never reached till now).

* Below is pasted from the failure at https://gitlab.com/nars1/YDBRust/-/jobs/3498581456

  ```
   Documenting yottadb v2.0.0 (/builds/nars1/YDBRust)
  error: unclosed HTML tag `u8`
    --> src/simple_api/mod.rs:18:18
     |
  18 | //! consume a Vec<u8> and return [`YDBResult<Vec<u8>>`][YDBResult]. The return Vec<u8> will either contain
     |                  ^^^^
     |
     = note: `-D rustdoc::invalid-html-tags` implied by `-D warnings`
  help: try marking as source code
  ```

* This is a warning from `cargo deadlinks`.

* This is fixed by using the `help:` suggestion above. That is, using back-quotes around `Vec<u8>`.