Fix build-imptp-rs job failure in YDBTest (due to d958832)
Background
----------
* The `build-imptp-rs` pipeline job failed (at https://gitlab.com/YottaDB/DB/YDBTest/-/jobs/3399535288)
  with the following symptom.

  ```
  .
  .
  --- stderr
  error: Found argument '--allowlist-type' which wasn't expected, or isn't valid in this context
  	Did you mean --blacklist-type?
  USAGE:
        bindgen [FLAGS] [OPTIONS] <header> -- <clang-args>...
  ```

Issue
-----
* d958832 had removed the `whitelist`/`blacklist` usages and replaced them with `allowlist`/`blocklist`
  usages. That was needed because the latest `bindgen-cli` (version `0.63.0`) removed support for those
  usages (see commit message of d958832 for details).

* But most other usages of YDBRust continue to use the package manager installed versions. The
  `build-imptp-rs` job in `YDBTest` used the YottaDB debian docker image. That is a Debian Bullseye
  image and the package manager installed version of `bindgen` there was `0.55.0` which is an old enough
  version that does not recognize these new `allowlist`/`blocklist` usages. And is why the job failed.

Fix
---
* The first step is to revert d958832 which is done in this commit.

* The next step is to find a different solution to the original problem in the `rust-no-vendor` job.
  And that is to install a specific version `0.62.0` of `bindgen-cli`. That version supported the
  `whitelist`/`blacklist` usages and so had no issues. That change is also done in this commit.

Future notes
------------
* In the future, when the YottaDB debian docker image has a version of bindgen that is greater than or
  equal to `0.63.0`, we can `revert` this commit and get back to using the latest `bindgen-cli` in the
  `rust-no-vendor` job.