Use allowlist/blocklist flags to bindgen (instead of the unsupported whitelist/blacklist)
Background
----------
* The nightly `rust-no-vendor` pipeline job started failing since Nov 22, 2022 with the following error.

  ```
  --- stderr
  error: Found argument '--whitelist-type' which wasn't expected, or isn't valid in this context
  	If you tried to supply `--whitelist-type` as a value rather than a flag, use `-- --whitelist-type`
  USAGE:
      bindgen [FLAGS] [OPTIONS] <header> -- <clang-args>...
  ```

Issue
-----
* Below is pasted from https://github.com/rust-lang/rust-bindgen/blob/master/CHANGELOG.md#removed-1
  and describes the related change to `bindgen` (will show up in release `0.63.0`).

  _The following deprecated methods and their equivalent CLI arguments were removed: whitelist_recursively,
  hide_type, blacklist_type, blacklist_function, blacklist_item, whitelisted_type, whitelist_type,
  whitelist_function, whitelisted_function, whitelist_var, whitelisted_var, unstable_rust._

Fix
---
* Therefore the fix for the pipeline failure is to start using the new terminology and remove references
  to the deprecated/unsupported terminology.

* Since the pipeline uses the `Nightly Rust` build in general and the failing job builds the latest `bindgen`,
  it caught this error before this change made it into a stable release.