Fix rust-latest pipeline failure due to clippy error in src/simple_api/mod.rs
Background
----------

* The `rust-latest` pipeline job [started failing in the pipeline](https://gitlab.com/YottaDB/Lang/YDBRust/-/jobs/5834233436) as follows

```plaintext
Compiling yottadb v2.0.0 (/builds/YottaDB/Lang/YDBRust)
1232error: accessing first element with `self.subscripts.get(0)`
1233 --> src/simple_api/mod.rs:230:30
1234 |
1235230 | if let Some(first) = self.subscripts.get(0) {
1236 | ^^^^^^^^^^^^^^^^^^^^^^ help: try: `self.subscripts.first()`
1237 |
1238 = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#get_first
1239 = note: `-D clippy::get-first` implied by `-D clippy::all`
1240 = help: to override `-D clippy::all` add `#[allow(clippy::get_first)]`
1241error: could not compile `yottadb` (lib) due to previous error
```

Issue
-----

Since May 2020, new Rust lint rule introduced: [_use slice.first() instead of slice.get(0) #8851_](https://github.com/rust-lang/rust-clippy/issues/8851)_,_ which causes Clippy to indicate error on previously accepted code

Fix
---

Subscript access changed from `.get(0)` to `.first()`, as Clippy suggested