Fix nightly warnings
These will hit stable in about 6 weeks, it's nice to fix them early.

Note that this does not fix `clippy::upper_case_acronyms` since doing so
would be a breaking change. See
https://github.com/rust-lang/rust-clippy/issues/6803 for more details.

Here are the warnings that were previously emitted:

```
warning: unnecessary trailing semicolon
    --> src/simple_api/mod.rs:1172:10
     |
1172 |         };
     |          ^ help: remove this semicolon
     |
     = note: `#[warn(redundant_semicolons)]` on by default
warning: panic message is not a string literal
   --> examples/threenp1.rs:127:30
    |
127 |             Err(x) => panic!(x),
    |                              ^
    |
    = note: `#[warn(non_fmt_panic)]` on by default
    = note: this is no longer accepted in Rust 2021
help: add a "{}" format string to Display the message
    |
127 |             Err(x) => panic!("{}", x),
    |                              ^^^^^
help: or use std::panic::panic_any instead
    |
127 |             Err(x) => std::panic::panic_any(x),
    |                       ^^^^^^^^^^^^^^^^^^^^^^
error: name `YDB` contains a capitalized acronym
   --> src/context_api/mod.rs:747:5
    |
747 |     YDB(YDBError),
    |     ^^^ help: consider making the acronym lowercase, except the initial letter: `Ydb`
    |
    = note: `-D clippy::upper-case-acronyms` implied by `-D clippy::all`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
```