Fix nightly clippy warning
This fixes the following warning:

```
error: replacing a value of type `T` with `T::default()` is better expressed using `std::mem::take`
--> src/context_api/mod.rs:535:9
|
35 | std::mem::replace(&mut self.context.buffer.borrow_mut(), Vec::new())
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using: `std::mem::take(&mut self.context.buffer.borrow_mut())`
|
= note: `-D clippy::mem-replace-with-default` implied by `-D clippy::all`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mem_replace_with_default
```

This was introduced by the update to 1.53, the latest stable. Since we support 1.40, and mem::take was introduced in 1.40, this does not increase the minimum Rust version.